from myagents.prompts.envs.query import (
    QUERY_SYSTEM_PROMPT, QUERY_DOC_PROMPT, QUERY_ORCHESTRATION_PROMPT, 
    QUERY_PLAN_AND_EXECUTE_PROMPT, QUERY_SELECT_PROMPT, QUERY_ERROR_PROMPT,
    NAME, PROFILE,
)

__all__ = [
    "QUERY_SYSTEM_PROMPT",
    "QUERY_DOC_PROMPT",
    "QUERY_ORCHESTRATION_PROMPT",
    "QUERY_PLAN_AND_EXECUTE_PROMPT",
    "QUERY_SELECT_PROMPT",
    "QUERY_ERROR_PROMPT",
    "NAME",
    "PROFILE",
]