from myagents.prompts.envs.query import (
    QUERY_SYSTEM_PROMPT, QUERY_DOC_PROMPT, QUERY_ORCHESTRATE_PROMPT, 
    QUERY_EXECUTE_PROMPT, QUERY_SELECT_PROMPT, QUERY_ERROR_PROMPT,
    NAME, PROFILE,
)

__all__ = [
    "QUERY_SYSTEM_PROMPT",
    "QUERY_DOC_PROMPT",
    "QUERY_ORCHESTRATE_PROMPT",
    "QUERY_EXECUTE_PROMPT",
    "QUERY_SELECT_PROMPT",
    "QUERY_ERROR_PROMPT",
    "NAME",
    "PROFILE",
]